### ISSUE TITLE
Nvidia DGX-SPARK部署生成的语音充满杂音

### ISSUE THREAD

**Issue by zdai** [index-tts/index-tts#496]
有没有在最新的DGX-SPARK上面部署？我能成功的inference但是生成的音频充满杂音。
我之前部署在mac mini上面v1.5，生成的语音没有任何问题，很干净。v1.5的版本照搬到DGX-SPARK上面后生成音频基本不可用。V2.0生成的也是同样的问题。

**Comment by zdai** [comment]
反复尝试后发现，如果我用torch 2.8 版本，torch.cuda.is_available() == False, 只能用CPU生成，结果语音没有杂音
如果我用torch 2.9的CPU only版本，就算是CPU生成，结果音频也是充满噪音，用torch 2.9+cu130版本，使用GPU生成，结果音频充满杂音。所以看起来像是torcuaudio 2.9的问题

**Comment by nzgnzg73** [comment]
"我建议您改用：
https://github.com/mirbehnam/Chatterbox-TTS-Server-windows-easyInstallation.git
（如您所提），根据我的经验，这个方案更优秀、更稳定。
这个系统能满足您的期望：
 * 最佳音质： 它能提供清晰（clean）的音频输出，就像您在 Mac mini 上使用 v1.5 所获得的那样。
 * 情感控制 (Emotion Control)： 您可以轻松控制语音的情感表达（如愤怒、悲伤、快乐等）。
 * 多语言支持： 它支持包括 23 种语言在内的多种语言。
请尝试使用它，它将对您的工作更有效。"

**Comment by jjmlovesgit** [comment]
DGX Test:

udo docker run --rm -it --gpus all \
--ipc=host \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
nvidia/cuda:12.9.0-devel-ubuntu22.04 \
bash -c "
apt-get update && \
apt-get install -y python3 python3-pip && \
echo '=== Installing PyTorch with dependencies ===' && \
pip3 install --pre torch --index-url https://download.pytorch.org/whl/test/cu129 && \
echo '=== Testing GB10 with PyTorch ===' && \
python3 -c \"
import torch
print('🎉 SUCCESS: PyTorch installed with dependencies!')
print('PyTorch version:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('CUDA version:', torch.version.cuda)
    print('GPU Name:', torch.cuda.get_device_name(0))
    capability = torch.cuda.get_device_capability(0)
    print('Compute Capability:', f'sm_{capability[0]}{capability[1]}')
    print('GPU Memory:', f'{torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB')
    
    # Test GPU operations
    print('Testing GPU operations...')
    x = torch.randn(1000, 1000).cuda()
    y = torch.randn(1000, 1000).cuda()
    z = torch.matmul(x, y)
    print('✅ GPU matrix multiplication successful!')
    print('Result shape:', z.shape)
    print('🎯 GB10 is fully operational with PyTorch + CUDA 12.9!')
else:
    print('❌ CUDA not available')
\""

result:

=== Testing GB10 with PyTorch ===
/usr/local/lib/python3.10/dist-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
🎉 SUCCESS: PyTorch installed with dependencies!
PyTorch version: 2.9.0+cu129
CUDA available: True
CUDA version: 12.9
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GB10 which is of cuda capability 12.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (8.0) - (12.0)
    
  warnings.warn(
GPU Name: NVIDIA GB10
Compute Capability: sm_121
GPU Memory: 119.7 GB
Testing GPU operations...
✅ GPU matrix multiplication successful!
Result shape: torch.Size([1000, 1000])
🎯 GB10 is fully operational with PyTorch + CUDA 12.9!

**Comment by nzgnzg73** [comment]
Hello 

nzgnzg73@gmail.com

**Comment by jjmlovesgit** [comment]
On DGX trying to do GPU but it is 



falling back to CPU and that works....

=== Starting IndexTTS with GB10 GPU acceleration ===
>> Be patient, it may take a while to run in CPU mode.
>> GPT weights restored from: /mnt/project/checkpoints/gpt.pth
[2025-10-19 05:23:48,860] [WARNING] [real_accelerator.py:209:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-10-19 05:23:48,861] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2025-10-19 05:23:49,739] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
GPT2InferenceModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
>> semantic_codec weights restored from: /root/.cache/huggingface/hub/models--amphion--MaskGCT/snapshots/265c6cef07625665d0c28d2faafb1415562379dc/semantic_codec/model.safetensors
cfm loaded
length_regulator loaded
gpt_layer loaded
>> s2mel weights restored from: /mnt/project/checkpoints/s2mel.pth
>> campplus_model weights restored from: /root/.cache/huggingface/hub/models--funasr--campplus/snapshots/fb71fe990cbf6031ae6987a2d76fe64f94377b7e/campplus_cn_common.bin
Loading weights from nvidia/bigvgan_v2_22khz_80band_256x
Removing weight norm...
>> bigvgan weights restored from: nvidia/bigvgan_v2_22khz_80band_256x
>> TextNormalizer loaded
>> bpe model loaded from: /mnt/project/checkpoints/bpe.model
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.
Example clicked: (14 values) = ['examples/voice_01.wav', 'Same as the voice reference', 'Translate for me, what is a surprise!', None, 1.0, '', 0, 0, 0, 0, 0, 0, 0, 0]
Emo control mode:0,weight:1,vec:None
>> starting inference...
Use the specified emotion vector
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.53.0. You should pass an instance of `Cache` instead, e.g. `past_key_values=DynamicCache.from_legacy_cache(past_key_values)`.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:23<00:00,  1.05it/s]
torch.Size([1, 75264])
>> gpt_gen_time: 75.02 seconds
>> gpt_forward_time: 0.95 seconds
>> s2mel_time: 23.93 seconds
>> bigvgan_time: 3.93 seconds
>> Total inference time: 108.13 seconds
>> Generated audio length: 3.41 seconds
>> RTF: 31.6801
>> wav file saved to: outputs/spk_1760851454.wav
^CKeyboard interruption in main thread... closing server.

**Comment by nzgnzg73** [comment]
I don't know much about the problem that is coming, one has come and he has defeated it, it is better than this, it is very good. Receive it on Gmail I will explain it to you in full detail 
nzgnzg73@gmail.com

**Comment by jjmlovesgit** [comment]
sudo docker run --rm -it --gpus all -p 7860:7860 \
--ipc=host \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
-v /home/mccormj/Applications/Indextts:/mnt/project \
-v /home/mccormj/.cache/huggingface:/root/.cache/huggingface \
nvidia/cuda:12.9.0-devel-ubuntu22.04 \
bash -c "
cd /mnt/project && \
echo '=== Installing system dependencies ===' && \
apt-get update && apt-get install -y python3 python3-pip espeak-ng ffmpeg && \
echo '=== Installing PyTorch ecosystem ===' && \
pip3 install torch==2.8.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/test/cu129 && \
echo '=== Installing core dependencies from pyproject.toml ===' && \
pip3 install transformers==4.52.1 tokenizers==0.21.0 safetensors==0.5.2 accelerate==1.8.1 && \
echo '=== Installing additional required dependencies ===' && \
pip3 install einops cn2an==0.5.22 cython==3.0.7 descript-audiotools==0.7.2 ffmpeg-python==0.2.0 g2p-en==2.1.0 jieba==0.42.1 json5==0.10.0 keras==2.9.0 librosa==0.10.2.post1 matplotlib==3.8.2 modelscope==1.27.0 munch==4.0.0 numba==0.58.1 numpy==1.26.2 omegaconf opencv-python==4.9.0.80 pandas==2.3.2 sentencepiece tqdm textstat && \
echo '=== Installing webui dependencies ===' && \
pip3 install gradio==5.45.0 && \
echo '=== Installing deepspeed dependencies ===' && \
pip3 install deepspeed==0.17.1 && \
echo '=== Testing imports ===' && \
python3 -c \"
try:
    import torch
    import torchaudio
    from transformers import __version__
    import einops
    import librosa
    import gradio
    import deepspeed
    print('✅ All imports successful')
    print('PyTorch version:', torch.__version__)
    print('Torchaudio version:', torchaudio.__version__)
    print('Transformers version:', __version__)
    print('CUDA available:', torch.cuda.is_available())
    if torch.cuda.is_available():
        print('GPU name:', torch.cuda.get_device_name(0))
        print('CUDA version:', torch.version.cuda)
except Exception as e:
    print('❌ Import failed:', e)
    import traceback
    traceback.print_exc()
\" && \
echo '=== Starting IndexTTS ===' && \
CUDA_VISIBLE_DEVICES=0 python3 webui.py --model_dir /mnt/project/checkpoints --fp16 --deepspeed"


Results:

✅ All imports successful
PyTorch version: 2.8.0+cu129
Torchaudio version: 2.8.0
Transformers version: 4.52.1
CUDA available: True
GPU name: NVIDIA GB10
CUDA version: 12.9
=== Starting IndexTTS ===

A Run:

>> starting inference...
Use the specified emotion vector
------------------------------------------------------
Free memory : 47.664494 (GigaBytes)  
Total memory: 119.699211 (GigaBytes)  
Requested memory: 0.541992 (GigaBytes) 
Setting maximum total tokens (input + output) to 1024 
WorkSpace: 0xf1d7e0000000 
------------------------------------------------------
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.53.0. You should pass an instance of `Cache` instead, e.g. `past_key_values=DynamicCache.from_legacy_cache(past_key_values)`.
100%|███████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 34.64it/s]
torch.Size([1, 64256])
>> gpt_gen_time: 3.59 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 0.73 seconds
>> bigvgan_time: 0.35 seconds
>> Total inference time: 7.35 seconds
>> Generated audio length: 2.91 seconds
>> RTF: 2.5237
>> wav file saved to: outputs/spk_1760873369.wav

<img width="1233" height="927" alt="Image" src="https://github.com/user-attachments/assets/149d1e73-bfbe-4cf2-af39-75d951cf1f66" />

**Comment by jjmlovesgit** [comment]
<img width="1650" height="1167" alt="Image" src="https://github.com/user-attachments/assets/634b148a-3870-462f-87c9-a56db2969549" />

**Comment by jjmlovesgit** [comment]
Sentence level creation for streaming...

Generating 1/7: The Visual Studio Code Dev Containers extension lets you use...
>> starting inference...
Use the specified emotion vector
100%|█████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 21.24it/s]
torch.Size([1, 170752])
>> gpt_gen_time: 7.06 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 1.20 seconds
>> bigvgan_time: 0.84 seconds
>> Total inference time: 9.33 seconds
>> Generated audio length: 7.74 seconds
>> RTF: 1.2049
>> wav file saved to: outputs/stream_1760880134_0.wav
📝 Generating 2/7: It allows you to open any folder inside (or mounted into) a ...
>> starting inference...
Use the specified emotion vector
100%|█████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 19.95it/s]
torch.Size([1, 185344])
>> gpt_gen_time: 7.85 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 1.28 seconds
>> bigvgan_time: 0.90 seconds
>> Total inference time: 10.27 seconds
>> Generated audio length: 8.41 seconds
>> RTF: 1.2218
>> wav file saved to: outputs/stream_1760880144_1.wav
📝 Generating 3/7: A devcontainer.json file in your project tells VS Code how t...
>> starting inference...
Use the specified emotion vector
100%|█████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 18.64it/s]
torch.Size([1, 210688])
>> gpt_gen_time: 9.09 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 1.37 seconds
>> bigvgan_time: 1.00 seconds
>> Total inference time: 11.74 seconds
>> Generated audio length: 9.56 seconds
>> RTF: 1.2286
>> wav file saved to: outputs/stream_1760880154_2.wav
📝 Generating 4/7: This container can be used to run an application or to separ...
>> starting inference...
Use the specified emotion vector
100%|█████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 21.41it/s]
torch.Size([1, 166400])
>> gpt_gen_time: 6.92 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 1.19 seconds
>> bigvgan_time: 0.81 seconds
>> Total inference time: 9.15 seconds
>> Generated audio length: 7.55 seconds
>> RTF: 1.2121
>> wav file saved to: outputs/stream_1760880166_3.wav
📝 Generating 5/7: Workspace files are mounted from the local file system or co...
>> starting inference...
Use the specified emotion vector
100%|█████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 23.94it/s]
torch.Size([1, 132864])
>> gpt_gen_time: 5.31 seconds
>> gpt_forward_time: 0.01 seconds
>> s2mel_time: 1.07 seconds

**Comment by nzgnzg73** [comment]
Very nice

**Comment by nzgnzg73** [comment]
Friend, can you help me? I don't have such heavy digestion. Low PC. What do you do that your voice caller has just turned on Can you give me its URL and share it? Meaning public url is a dog local a public url what can help

**Comment by nzgnzg73** [comment]
![Image](https://github.com/user-attachments/assets/8bc63a75-ff9a-4c23-bf2c-964505e5a428)
will you help?

**Comment by jjmlovesgit** [comment]
Quick 10 sec DGX screen recording to share actual output...

fmpeg -f x11grab -video_size 1255x1252 -i :1+2184,136 -f pulse -i default -t 10 firefox_recording.mp4

https://github.com/user-attachments/assets/dffa7cc5-2865-4bb0-914b-9fcf1546cdf1

**Comment by nzgnzg73** [comment]
I don't understand you, please explain.

**Comment by jjmlovesgit** [comment]
The NVIDIA Quadro P2000 has Pascal SM architecture (streaming multi-processor design) with a compute capability of 6.1. Since PyTorch no longer ships with binaries supporting this older compute capability, I am sorry but I would not know how to get Index2-tts to run on that GPU.

**Comment by jjmlovesgit** [comment]
Key Lessons Learned for IndexTTS on GPU:
1. CUDA & PyTorch Compatibility

    Use CUDA 12.9.0 with PyTorch 2.8.0 (test/cu129 channel)

    Critical: Match exact CUDA version with PyTorch build

    Command: pip3 install torch==2.8.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/test/cu129

2. Dependency Management

    Install in correct order: System deps → PyTorch → Core ML → Audio processing → UI

    Essential system packages: python3 python3-pip espeak-ng ffmpeg

    Core ML stack: transformers==4.52.1 tokenizers==0.21.0 safetensors==0.5.2 accelerate==1.8.1

    Audio processing: librosa==0.10.2.post1 soundfile numba==0.58.1

    Web UI: gradio==5.45.0

**Comment by nzgnzg73** [comment]
Brother, I do not have such a big laptop, it is a low end laptop which has very little gpu inside. Can you help me? Can you give the public URL? How many gpu graphic cards do you have installed inside the PC?

**Comment by fengcunhan** [comment]
> 反复尝试后发现，如果我用torch 2.8 版本，torch.cuda.is_available() == False, 只能用CPU生成，结果语音没有杂音 如果我用torch 2.9的CPU only版本，就算是CPU生成，结果音频也是充满噪音，用torch 2.9+cu130版本，使用GPU生成，结果音频充满杂音。所以看起来像是torcuaudio 2.9的问题

我在 Mac M3 Pro 上也有相同的问题，降级到 2.8 以后就解决了。

**Comment by xiaohongai** [comment]
> sudo docker run --rm -it --gpus all -p 7860:7860 --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -v /home/mccormj/Applications/Indextts:/mnt/project -v /home/mccormj/.cache/huggingface:/root/.cache/huggingface nvidia/cuda:12.9.0-devel-ubuntu22.04 bash -c " cd /mnt/project && echo '=== Installing system dependencies ===' && apt-get update && apt-get install -y python3 python3-pip espeak-ng ffmpeg && echo '=== Installing PyTorch ecosystem ===' && pip3 install torch==2.8.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/test/cu129 && echo '=== Installing core dependencies from pyproject.toml ===' && pip3 install transformers==4.52.1 tokenizers==0.21.0 safetensors==0.5.2 accelerate==1.8.1 && echo '=== Installing additional required dependencies ===' && pip3 install einops cn2an==0.5.22 cython==3.0.7 descript-audiotools==0.7.2 ffmpeg-python==0.2.0 g2p-en==2.1.0 jieba==0.42.1 json5==0.10.0 keras==2.9.0 librosa==0.10.2.post1 matplotlib==3.8.2 modelscope==1.27.0 munch==4.0.0 numba==0.58.1 numpy==1.26.2 omegaconf opencv-python==4.9.0.80 pandas==2.3.2 sentencepiece tqdm textstat && echo '=== Installing webui dependencies ===' && pip3 install gradio==5.45.0 && echo '=== Installing deepspeed dependencies ===' && pip3 install deepspeed==0.17.1 && echo '=== Testing imports ===' && python3 -c " try: import torch import torchaudio from transformers import **version** import einops import librosa import gradio import deepspeed print('✅ All imports successful') print('PyTorch version:', torch.**version**) print('Torchaudio version:', torchaudio.**version**) print('Transformers version:', **version**) print('CUDA available:', torch.cuda.is_available()) if torch.cuda.is_available(): print('GPU name:', torch.cuda.get_device_name(0)) print('CUDA version:', torch.version.cuda) except Exception as e: print('❌ Import failed:', e) import traceback traceback.print_exc() " && echo '=== Starting IndexTTS ===' && CUDA_VISIBLE_DEVICES=0 python3 webui.py --model_dir /mnt/project/checkpoints --fp16 --deepspeed"
> 
> Results:
> 
> ✅ All imports successful PyTorch version: 2.8.0+cu129 Torchaudio version: 2.8.0 Transformers version: 4.52.1 CUDA available: True GPU name: NVIDIA GB10 CUDA version: 12.9 === Starting IndexTTS ===
> 
> A Run:
> 
> > > starting inference...
> > > Use the specified emotion vector
> 
> ## Free memory : 47.664494 (GigaBytes)
> Total memory: 119.699211 (GigaBytes)
> Requested memory: 0.541992 (GigaBytes)
> Setting maximum total tokens (input + output) to 1024
> WorkSpace: 0xf1d7e0000000
> 
> Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.53.0. You should pass an instance of `Cache` instead, e.g. `past_key_values=DynamicCache.from_legacy_cache(past_key_values)`. 100%|███████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 34.64it/s] torch.Size([1, 64256])
> 
> > > gpt_gen_time: 3.59 seconds
> > > gpt_forward_time: 0.01 seconds
> > > s2mel_time: 0.73 seconds
> > > bigvgan_time: 0.35 seconds
> > > Total inference time: 7.35 seconds
> > > Generated audio length: 2.91 seconds
> > > RTF: 2.5237
> > > wav file saved to: outputs/spk_1760873369.wav
> 
> <img alt="Image" width="1233" height="927" src="https://private-user-images.githubusercontent.com/47751509/502969738-149d1e73-bfbe-4cf2-af39-75d951cf1f66.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2ODAxOTksIm5iZiI6MTc2MzY3OTg5OSwicGF0aCI6Ii80Nzc1MTUwOS81MDI5Njk3MzgtMTQ5ZDFlNzMtYmZiZS00Y2YyLWFmMzktNzVkOTUxY2YxZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDIzMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmFlMGRhNzA3MTg5OTkwMjE5OTJkMGMxYjUzOWI5ZDYyYWUyYjMyMTNhMzRhNWJlNTZiMzQyNWY5YmY2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eQ40Rm7Z34M4IExjQ7UFBDLx2Qy65ydymm_21N0d9So">

help me ,dgx spark
>> bigvgan weights restored from: nvidia/bigvgan_v2_22khz_80band_256x
Traceback (most recent call last):
  File "/mnt/project/webui.py", line 56, in <module>
    tts = IndexTTS2(model_dir=cmd_args.model_dir,
  File "/mnt/project/indextts/infer_v2.py", line 171, in __init__
    self.normalizer.load()
  File "/mnt/project/indextts/utils/front.py", line 100, in load
    from tn.chinese.normalizer import Normalizer as NormalizerZh
ModuleNotFoundError: No module named 'tn'

**Comment by jjmlovesgit** [comment]
here is link to docker prebuilt to run on DGX spark I uploaded here on dockerhub

[jimmy_original.mp3](https://github.com/user-attachments/files/23776792/jimmy_original.mp3)

https://hub.docker.com/repository/docker/mccorji/indextts2_webui/general

mccormj@spark-c20d:~$ sudo docker run --rm -it --gpus all -p 7860:7860 \
  --ipc=host \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -v /home/mccormj/home/mccormj/Applications/Indextts2:/mnt/project \
  -v /home/mccormj/.cache/huggingface:/root/.cache/huggingface \
  indextts2_webui \
  bash -c "export PYTHONPATH=/mnt/project:\$PYTHONPATH && python3 /mnt/project/webui.py --model_dir /mnt/project/checkpoints --fp16 --deepspeed"
[sudo] password for mccormj: 


==========
== CUDA ==
==========

CUDA Version 12.9.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

>> GPT weights restored from: /mnt/project/checkpoints/gpt.pth
>> Failed to load DeepSpeed. Falling back to normal inference. Error: No module named 'deepspeed'
GPT2InferenceModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
>> semantic_codec weights restored from: /root/.cache/huggingface/hub/models--amphion--MaskGCT/snapshots/265c6cef07625665d0c28d2faafb1415562379dc/semantic_codec/model.safetensors
cfm loaded
length_regulator loaded
gpt_layer loaded
>> s2mel weights restored from: /mnt/project/checkpoints/s2mel.pth
>> campplus_model weights restored from: /root/.cache/huggingface/hub/models--funasr--campplus/snapshots/fb71fe990cbf6031ae6987a2d76fe64f94377b7e/campplus_cn_common.bin
Loading weights from nvidia/bigvgan_v2_22khz_80band_256x
Removing weight norm...
>> bigvgan weights restored from: nvidia/bigvgan_v2_22khz_80band_256x
>> TextNormalizer loaded
>> bpe model loaded from: /mnt/project/checkpoints/bpe.model
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.

<img width="1682" height="1762" alt="Image" src="https://github.com/user-attachments/assets/c5f453fe-14ce-42f0-aa39-69b18d3fe356" />

**Comment by jjmlovesgit** [comment]
Find this block and comment out every line inside it:
code Python

    
MAX_LENGTH_TO_USE_SPEED = 70
example_cases = []
with open("examples/cases.jsonl", "r", encoding="utf-8") as f: # <- This line fails
    for line in f:
        line = line.strip()
        if not line:
            continue
        example = json.loads(line)
        if example.get("emo_audio",None):
            emo_audio_path = os.path.join("examples",example["emo_audio"])
        else:
            emo_audio_path = None

        example_cases.append([os.path.join("examples", example.get("prompt_audio", "sample_prompt.wav")),
                              EMO_CHOICES_ALL[example.get("emo_mode",0)],
                              example.get("text"),
                             emo_audio_path,
                             example.get("emo_weight",1.0),
                             example.get("emo_text",""),
                             example.get("emo_vec_1",0),
                             example.get("emo_vec_2",0),
                             example.get("emo_vec_3",0),
                             example.get("emo_vec_4",0),
                             example.get("emo_vec_5",0),
                             example.get("emo_vec_6",0),
                             example.get("emo_vec_7",0),
                             example.get("emo_vec_8",0),
                             ])

  

Change the entire block to this (or just ensure example_cases = [] is the only executable line):
code Python

    
MAX_LENGTH_TO_USE_SPEED = 70
example_cases = []
# --- START OF ORIGINAL EXAMPLES BLOCK (COMMENTED OUT) ---
# with open("/mnt/project/examples/cases.jsonl", "r", encoding="utf-8") as f:
#     for line in f:
#         line = line.strip()
#         if not line:
#             continue
#         example = json.loads(line)
#         if example.get("emo_audio",None):
#             emo_audio_path = os.path.join("examples",example["emo_audio"])
#         else:
#             emo_audio_path = None

#         example_cases.append([os.path.join("examples", example.get("prompt_audio", "sample_prompt.wav")),
#                               EMO_CHOICES_ALL[example.get("emo_mode",0)],
#                               example.get("text"),
#                              emo_audio_path,
#                              example.get("emo_weight",1.0),
#                              example.get("emo_text",""),
#                              example.get("emo_vec_1",0),
#                              example.get("emo_vec_2",0),
#                              example.get("emo_vec_3",0),
#                              example.get("emo_vec_4",0),
#                              example.get("emo_vec_5",0),
#                              example.get("emo_vec_6",0),
#                              example.get("emo_vec_7",0),
#                              example.get("emo_vec_8",0),
#                              ])
# --- END OF ORIGINAL EXAMPLES BLOCK (COMMENTED OUT) ---

  

Ensure the get_example_cases function is called safely (Lines 98, 107):

Verify that in this line:
code Python

        
    example_table = gr.Dataset(label="Examples",
        samples_per_page=20,
        samples=get_example_cases(include_experimental=False),
        # ...

      

    The get_example_cases() function handles an empty list (example_cases = []) gracefully, which it does.

Rerun the FINAL Execution

After saving the file with the commented-out block, rerun the final command. The script will now load with an empty list of examples, completely bypassing the file read operation.
